// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using TesteJSL.Models;

#nullable disable

namespace TesteJSL.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20230713134840_TestJSL.Initial")]
    partial class TestJSLInitial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TesteJSL.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("Id");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ativo")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("Ativo");

                    b.Property<string>("Nome")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("Nome");

                    b.HasKey("Id");

                    b.ToTable("tbCliente");
                });

            modelBuilder.Entity("TesteJSL.Models.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("Id");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClienteId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("DataPedido")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DataPedido");

                    b.Property<int>("IdCliente")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("IdCliente");

                    b.Property<string>("Status")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("Status");

                    b.Property<float>("TotalPedido")
                        .HasColumnType("BINARY_FLOAT")
                        .HasColumnName("TotalPedido");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("tbPedido");
                });

            modelBuilder.Entity("TesteJSL.Models.PedidoItens", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("Id");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PedidoId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("IdPedido");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("IdProduto");

                    b.Property<int>("Quantidade")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("Quantidade");

                    b.Property<float>("ValorProduto")
                        .HasColumnType("BINARY_FLOAT")
                        .HasColumnName("ValorProduto");

                    b.Property<float>("ValorTotal")
                        .HasColumnType("BINARY_FLOAT")
                        .HasColumnName("ValorTotal");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoId");

                    b.ToTable("tbPedidoProdutos");
                });

            modelBuilder.Entity("TesteJSL.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("Id");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ativo")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("Ativo");

                    b.Property<string>("Nome")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("Nome");

                    b.Property<float>("ValorProduto")
                        .HasColumnType("BINARY_FLOAT")
                        .HasColumnName("ValorProduto");

                    b.HasKey("Id");

                    b.ToTable("tbProduto");
                });

            modelBuilder.Entity("TesteJSL.Models.Pedido", b =>
                {
                    b.HasOne("TesteJSL.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("TesteJSL.Models.PedidoItens", b =>
                {
                    b.HasOne("TesteJSL.Models.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");
                });
#pragma warning restore 612, 618
        }
    }
}
